In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Ramita\Downloads\structured_data.csv")
print(df.head())  # Display first few rows

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520
1       2  CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520
2       3  CA-2016-138688  2016-06-12  2016-06-16    Second Class    DV-13045
3       4  US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335
4       5  US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

In [5]:
import pandas as pd

# Convert "Order Date" to datetime format
df["Order Date"] = pd.to_datetime(df["Order Date"])

# Filter for year 2017 and Ship Mode "Second Class"
df_2017_second_class = df[(df["Order Date"].dt.year == 2017) & (df["Ship Mode"] == "Second Class")]

# Display first few rows
df_2017_second_class.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
23,24,US-2017-156909,2017-07-16,2017-07-18,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,0.3,-1.0196
34,35,CA-2017-107727,2017-10-19,2017-10-23,Second Class,MA-17560,Matt Abelman,Home Office,United States,Houston,...,77095,Central,OFF-PA-10000249,Office Supplies,Paper,Easy-staple paper,29.472,3,0.2,9.9468
71,72,CA-2017-114440,2017-09-14,2017-09-17,Second Class,TB-21520,Tracy Blumstein,Consumer,United States,Jackson,...,49201,Central,OFF-PA-10004675,Office Supplies,Paper,Telephone Message Books with Fax/Mobile Sectio...,19.050,3,0.0,8.7630
85,86,CA-2017-140088,2017-05-28,2017-05-30,Second Class,PO-18865,Patrick O'Donnell,Consumer,United States,Columbia,...,29203,South,FUR-CH-10000863,Furniture,Chairs,Novimex Swivel Fabric Task Chair,301.960,2,0.0,33.2156
96,97,CA-2017-161018,2017-11-09,2017-11-11,Second Class,PN-18775,Parhena Norris,Home Office,United States,New York City,...,10009,East,FUR-FU-10000629,Furniture,Furnishings,9-3/4 Diameter Round Wall Clock,96.530,7,0.0,40.5426

In [1]:
import pandas as pd

# Load CSV file
file_path = r"C:\Users\Ramita\Desktop\Rami.csv"
df = pd.read_csv(file_path)

# Display basic info
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     72 non-null     float64
 1   brand_name     72 non-null     object
 2   title          72 non-null     object
 3   current_price  72 non-null     float64
 4   quantity       72 non-null     float64
 5   date           73 non-null     int64
 6   currency       72 non-null     object
 7   rrp            36 non-null     float64
 8   productCode    72 non-null     float64
 9   productType    72 non-null     object
 10  sales          72 non-null     float64
dtypes: float64(6), int64(1), object(4)
memory usage: 6.4+ KB

,product_id,brand_name,title,current_price,quantity,date,currency,rrp,productCode,productType,sales
0,204499665.0,Replay,Replay t-shirt in white,72.0,70.0,2000,USD,100.0,127434315.0,Product,5040.0
1,203420859.0,Jack & Jones,Jack & Jones script logo t-shirt in white,17.0,20.0,2026,USD,21.0,121133019.0,Product,340.0
2,204285229.0,Jack & Jones,Jack & Jones logo polo in pale green,34.0,35.0,2000,USD,43.0,126403589.0,Product,1190.0
3,202261918.0,Don't Think Twice,DTT denim board shorts in light blue,31.0,30.0,2003,USD,42.0,116069818.0,Product,930.0
4,202191610.0,Another Influence,Another Influence towelling shorts co-ord in m...,23.0,25.0,2004,USD,48.0,115976447.0,Product,575.0